config/routes.rb
Rails.application.routes.draw do

  resources :special_items
  resources :return_items
  resources :homepages
  devise_for :admins
  resources :adminpages
  resources :items
  resources :items do
  resources :comments
  end
  resources :carts
  resources :wishlists
  resources :orders
  match '/users',   to: 'users#index',via: 'get'
  match "/users/:id" => "users#show", via: 'get'
  match "/users/:id/edit" => "users#edit", via: 'get'
  match "/users/new" => "users#new", via: 'get'
  
  devise_for :users ,:path_prefix => 'my'
  resources :users

  get '/transaction', to: 'transaction#index'
  get '/quicktransaction', to: 'quicktransaction#index'
  get '/returnrequestprocess', to: 'returnrequestprocess#index'
  get '/specialrequestprocess', to: 'specialrequestprocess#index'
  get '/otp', to: 'otp#index'
  get '/clearCart', to: 'clear_cart#index'
  post "otp_enter", to: 'otp#getNum'
  
  root to:"homepages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adminpage.rb
class Adminpage < ApplicationRecord
 	
 	attr_readonly :mail_id, :password	
    validates :CVV,
    	presence: true,
    	length: {maximum: 3},
    	on: :edit,
    	allow_nil: false
    validates :Credit_card_number,
    	presence: true,
    	length: {maximum: 16},
    	on: :edit,
    	allow_nil: false
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :item
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
    has_many :comments, dependent: :destroy
    validates_presence_of :name
    validates_presence_of :category
    validates_presence_of :brand
    validates_presence_of :price
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/return_item.rb
class ReturnItem < ApplicationRecord
end

app/models/special_item.rb
class SpecialItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/special_items_controller.rb
class SpecialItemsController < InheritedResources::Base

  def index
    @oc, @cc, @wc = calculate_counts()
    if params[:status_id]
      if current_user.is_admin
        @special_items = SpecialItem.where(["specialItemStatus = ?", params[:status_id]])
      else
        @special_items = SpecialItem.where(["specialUserId = ?", current_user.id]).where(["specialItemStatus = ?", params[:status_id]])
      end
    end
  end
  private

    def special_item_params
      params.permit(:specialUserId, :specialItemid, :specialItemTransactionId, :specialQuantity, :refundAmount, :specialItemStatus)
    end

end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clear_cart_helper.rb
module ClearCartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/special_items_helper.rb
module SpecialItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/special_items/_form.html.erb
<%= form_with(model: special_item, local: true) do |form| %>
  <% if special_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(special_item.errors.count, "error") %> prohibited this special_item from being saved:</h2>

      <ul>
        <% special_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :specialUserId %>
    <%= form.number_field :specialUserId %>
  </div>

  <div class="field">
    <%= form.label :specialItemid %>
    <%= form.number_field :specialItemid %>
  </div>

  <div class="field">
    <%= form.label :specialItemTransactionId %>
    <%= form.text_field :specialItemTransactionId %>
  </div>

  <div class="field">
    <%= form.label :specialQuantity %>
    <%= form.number_field :specialQuantity %>
  </div>

  <div class="field">
    <%= form.label :refundAmount %>
    <%= form.text_field :refundAmount %>
  </div>

  <div class="field">
    <%= form.label :specialItemStatus %>
    <%= form.check_box :specialItemStatus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/special_items/edit.html.erb
<h1>Editing Special Item</h1>

<%= render 'form', special_item: @special_item %>

<%= link_to 'Show', @special_item %> |
<%= link_to 'Back', special_items_path %>

app/views/special_items/index.html.erb
<!--<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3 rounded-bottom">
  <div class ="container">
    <div class="navbar-nav">
      <%= link_to "Store", items_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Wishlists (#{@wc})", wishlists_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Cart (#{@cc})", carts_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Orders (#{@oc})", orders_url, method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Items Returned", return_items_url(:status_id => 1), method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Rejected Special Requests", special_items_url(:status_id => 2), method: "get", :class=>"nav-item nav-link"%>
      <% if current_user.is_admin == true %>
      <%= link_to "Return Requests", return_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Special Requests", special_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link"%>
      <% end %>
    </div>
  </div>
</nav>-->

<!--<h1>Special Items</h1>-->
<% if @special_items%>
  <table class = "table table-hover">
    <thead>
      <tr>
        <% if current_user.is_admin %>
          <th>User</th>
        <% end %>
        <th>Item Id</th>
        <th>TransactionID</th>
        <th>Qty</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @special_items.each do |special_item| %>
        <tr>
          <% if current_user.is_admin %>
            <td><%= User.where(:id => special_item.specialUserId).last.name %></td>
          <% end %>
          <td><%= Item.where(:id => special_item.specialItemid).last.name %></td>
          <td><%= special_item.specialItemTransactionId %></td>
          <td><%= special_item.specialQuantity %></td>
          <td><%= special_item.refundAmount %></td>
          <!--<td><%#= link_to 'Show', special_item %></td>
          <td><%#= link_to 'Edit', edit_special_item_path(special_item) %></td>
          <td><%#= link_to 'Destroy', special_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          <% if special_item.select("specialItemStatus").last.specialItemStatus == 0 %>
            <td><%= link_to 'Approve', specialrequestprocess_url(:is_approved => "yes", :item_id => special_item.specialItemid, :user_id => special_item.specialUserId, :tid => special_item.specialItemTransactionId), :method => "get", :class => "btn btn-outline-primary" %></td>
            <td><%= link_to 'Reject', specialrequestprocess_url(:is_approved => "no", :item_id => special_item.specialItemid, :user_id => special_item.specialUserId, :tid => special_item.specialItemTransactionId), :method => "get", :class => "btn btn-outline-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% else%>
  <h3>The list is empty.</h3>
<% end %>

<%= link_to 'Back', items_path , :class => "btn btn-primary"%>

app/views/special_items/new.html.erb
<h1>New Special Item</h1>

<%= render 'form', special_item: @special_item %>

<%= link_to 'Back', special_items_path %>

app/views/special_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialuserid:</strong>
  <%= @special_item.specialUserId %>
</p>

<p>
  <strong>Specialitemid:</strong>
  <%= @special_item.specialItemid %>
</p>

<p>
  <strong>Specialitemtransactionid:</strong>
  <%= @special_item.specialItemTransactionId %>
</p>

<p>
  <strong>Specialquantity:</strong>
  <%= @special_item.specialQuantity %>
</p>

<p>
  <strong>Refundamount:</strong>
  <%= @special_item.refundAmount %>
</p>

<p>
  <strong>Specialitemstatus:</strong>
  <%= @special_item.specialItemStatus %>
</p>

<%= link_to 'Edit', edit_special_item_path(@special_item) %> |
<%= link_to 'Back', special_items_path %>