config/routes.rb
Rails.application.routes.draw do

  resources :special_items
  resources :return_items
  resources :homepages
  devise_for :admins
  resources :adminpages
  resources :items
  resources :items do
  resources :comments
  end
  resources :carts
  resources :wishlists
  resources :orders
  match '/users',   to: 'users#index',via: 'get'
  match "/users/:id" => "users#show", via: 'get'
  match "/users/:id/edit" => "users#edit", via: 'get'
  match "/users/new" => "users#new", via: 'get'
  
  devise_for :users ,:path_prefix => 'my'
  resources :users

  get '/transaction', to: 'transaction#index'
  get '/quicktransaction', to: 'quicktransaction#index'
  get '/returnrequestprocess', to: 'returnrequestprocess#index'
  get '/specialrequestprocess', to: 'specialrequestprocess#index'
  get '/otp', to: 'otp#index'
  get '/clearCart', to: 'clear_cart#index'
  post "otp_enter", to: 'otp#getNum'
  
  root to:"homepages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adminpage.rb
class Adminpage < ApplicationRecord
 	
 	attr_readonly :mail_id, :password	
    validates :CVV,
    	presence: true,
    	length: {maximum: 3},
    	on: :edit,
    	allow_nil: false
    validates :Credit_card_number,
    	presence: true,
    	length: {maximum: 16},
    	on: :edit,
    	allow_nil: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :item
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
    has_many :comments, dependent: :destroy
    validates_presence_of :name
    validates_presence_of :category
    validates_presence_of :brand
    validates_presence_of :price
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/return_item.rb
class ReturnItem < ApplicationRecord
end

app/models/special_item.rb
class SpecialItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@user = User.all
  end

  def new
    @user= user.new
  end

  def create
    @user = user.new(params[:user])
    if @user.save
        redirect_to users_path, notice: 'User created.'
    else
      render :action => :new
    end
  end
  
 def show
  @user = User.find(params[:id])
 end
  
 def destroy
     @user = User.find(params[:id])
     @user.destroy
     redirect_to users_path, notice: 'User deleted.'
 end

  def edit
     @user = User.find(params[:id])
  end


   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to users_path, notice: 'User deleted.'
     else
       render 'edit'
     end
   end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :phone_number , :date_of_birth, :address, :credit_card_number, :name_on_card , :expiration_date,:CVV)
  end


end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clear_cart_helper.rb
module ClearCartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/users/edit.html.erb
<h2>Edit User</h2>

   <%= form_for(@user) do |f| %>

   <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email%>
      </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth, :start_year => 1900%>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :credit_card_number %>
    <%= f.number_field :credit_card_number,max: 9999999999999999, min:1000000000000000%>
  </div>

  <div class="field">
    <%= f.label :name_on_card %>
    <%= f.text_field :name_on_card %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date, :discard_day => true, :use_month_numbers => true %>
  </div>

  <div class="field">
    <%= f.label :CVV %>
    <%= f.number_field :CVV, {min: 100, max: 999, size: "3"} %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<!--<h1> Registered Users </h1>

<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.name %> 
  <% if user.is_admin == false %>
  <%= link_to 'Show ', user_path(user) %>
  <%= link_to 'Edit', edit_user_path(user)%>
  <%= link_to "Destroy", user, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
  <pre> <%= user.email%><br/></pre>
<% end %>

<br>

<%= link_to "Create user", new_user_path %>

<br>

<br>

<%= link_to 'Back', items_path %>
-->
<div class = "row">
  <div class = "col-md-5">
    <h1> Registered Users </h1>
  </div>
  <div class = "col-md-3">
    <%#= link_to 'Create User', items_path, :class => "btn btn-primary" %>
  </div>
  <div class = "col-md-4">
  </div>
</div>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan = "2" >Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users = User.where(:is_admin => false) %>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %> </td>
        <td><%= user.email%> </td>
        <td><%= link_to 'Show', user_path(user), :class => "btn btn-warning" %>
          <%= link_to 'Edit', edit_user_path(user), :class => "btn btn-warning" %>
          <%= link_to "X", user, method: :delete, data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', items_path, :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h2>Create User</h2>

<%= form_for(@user) do |f| %>

   <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email%>
   </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth, :start_year => 1900%>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :credit_card_number %>
    <%= f.number_field :credit_card_number,max: 9999999999999999, min:1000000000000000%>
  </div>

  <div class="field">
    <%= f.label :name_on_card %>
    <%= f.text_field :name_on_card %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date, :discard_day => true, :use_month_numbers => true %>
  </div>

  <div class="field">
    <%= f.label :CVV %>
    <%= f.number_field :CVV, {min: 100, max: 999, size: "3"} %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<table style="width:100%">
  <tr>
    <td style="width:50%"><h1>User Details</h1></td>
    <td style="width:50%;text-align:right"><h1><%= %></h1></td>
  </tr>
</table>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone Number:</strong>user
  <%= @user.phone_number %>
</p>

<p>
  <strong>Date of birth</strong>
  <%= @user.date_of_birth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Credit card number:</strong>
  <%= @user.credit_card_number %>
</p>

<p>
  <strong>Name on card:</strong>
  <%= @user.name_on_card %>
</p>

<p>
  <strong>Expiration date</strong>
  <%= @user.expiration_date %>
</p>

<p>
  <strong>CVV:</strong>
  <%= @user.CVV %>
</p>

<br>

<%= link_to 'Back', users_path %>