config/routes.rb
Rails.application.routes.draw do

  resources :special_items
  resources :return_items
  resources :homepages
  devise_for :admins
  resources :adminpages
  resources :items
  resources :items do
  resources :comments
  end
  resources :carts
  resources :wishlists
  resources :orders
  match '/users',   to: 'users#index',via: 'get'
  match "/users/:id" => "users#show", via: 'get'
  match "/users/:id/edit" => "users#edit", via: 'get'
  match "/users/new" => "users#new", via: 'get'
  
  devise_for :users ,:path_prefix => 'my'
  resources :users

  get '/transaction', to: 'transaction#index'
  get '/quicktransaction', to: 'quicktransaction#index'
  get '/returnrequestprocess', to: 'returnrequestprocess#index'
  get '/specialrequestprocess', to: 'specialrequestprocess#index'
  get '/otp', to: 'otp#index'
  get '/clearCart', to: 'clear_cart#index'
  post "otp_enter", to: 'otp#getNum'
  
  root to:"homepages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adminpage.rb
class Adminpage < ApplicationRecord
 	
 	attr_readonly :mail_id, :password	
    validates :CVV,
    	presence: true,
    	length: {maximum: 3},
    	on: :edit,
    	allow_nil: false
    validates :Credit_card_number,
    	presence: true,
    	length: {maximum: 16},
    	on: :edit,
    	allow_nil: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :item
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
    has_many :comments, dependent: :destroy
    validates_presence_of :name
    validates_presence_of :category
    validates_presence_of :brand
    validates_presence_of :price
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/return_item.rb
class ReturnItem < ApplicationRecord
end

app/models/special_item.rb
class SpecialItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  before_action :initialize_search, only: :index
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @items = Item.order(sort_column + " " + sort_direction)
    if current_user
      #@oc, @cc, @wc = calculate_counts()
      if current_user.is_admin
        @isAdmin = true
      else
        @isUser = true
      end
    else
      @visitor = true
    end
    handle_filters
    initialize_search
    if params[:is_subscribing]
      SubscriptionMailer.with(user_id: current_user.id, item_id: params[:item_id]).subscription_email.deliver_now!
      respond_to do |format|
        format.html { redirect_to items_url, notice: 'Item was successfully subscribed and mail has been sent.' }
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #@username = User.find(params[:uid]).name
    @oc, @cc, @wc = calculate_counts()
  end

  # GET /items/new
  def new
    @oc, @cc, @wc = calculate_counts()
    params[:remaining_quantity] = params[:quantity]
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @oc, @cc, @wc = calculate_counts()
  end

  # POST /items
  # POST /items.json
  def create
    @oc, @cc, @wc = calculate_counts()
    params[:item][:remaining_quantity] = params[:item][:quantity]
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :category, :quantity, :description, :remaining_quantity, :price, :tax_slab, :special_item, :age_restricted, :brand, :photo, :is_subscribing)
    end

    def sort_column
      Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    # Only allow a list of trusted parameters through.

    def initialize_search
      
      session[:filter] = params[:filter]
      params[:filter_option] = nil if params[:filter_option] == ""
      session[:filter_option] = params[:filter_option]
    end

    def handle_filters
      if session[:filter]== "category"
        
        if session[:filter_option]== session[:filter_option] && session[:filter_option] != nil && session[:filter_option] != "All"
          @items = @items.where(category: session[:filter_option])
          
        elsif session[:filter_option]== "All" 
          @items=@items
        end
      elsif session[:filter]=="brand"
        if session[:filter_option]== session[:filter_option] && session[:filter_option] != nil && session[:filter_option] != "All"
          @items = @items.where(brand: session[:filter_option])
        elsif session[:filter_option]== "All" 
          @items=@items
        end
      elsif session[:filter]=="remaining_quantity"
        
        if session[:filter_option]== "only_available"
          @items = @items
          
        end
      end
    end

end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clear_cart_helper.rb
module ClearCartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
  <%= form.label :brand %>
  <%= form.text_field :brand %>
  </div>

  <div class="field">
  <%= form.label :description %>
  <%= form.text_field :description %>
  </div>

  <div class="field">
  <%= form.label :quantity %>
  <%= form.text_field :quantity %>
  </div>

  <div class="field">
  <%= form.label :price %>
  <%= form.text_field :price %>
  </div>
  
  <div class="field">
  <%= form.label :tax_slab %>
  <%= form.text_field :tax_slab %>
  </div>

  <div class="field">
  <%= form.label :special_item %>
  <%= form.check_box  :special_item %>
  </div>

  <div class="field">
  <%= form.label :age_restricted %>
  <%= form.check_box :age_restricted %>
  </div>

  <p>
  <%= form.label :photo %>
  <%= form.file_field :photo %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
  

<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!--<nav class=" shadow-top navbar navbar-expand-md navbar-dark bg-dark mb-3 rounded-bottom">
  <div class ="container">
    <div class="  navbar-nav">
    <% if current_user %>
      <%= link_to "Store", items_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Wishlists (#{@wc})", wishlists_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Cart (#{@cc})", carts_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Orders (#{@oc})", orders_url, method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Items Returned", return_items_url(:status_id => 1), method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Rejected Special Requests", special_items_url(:status_id => 2), method: "get", :class=>"nav-item nav-link"%>
      <% if current_user.is_admin == true %>
      <%= link_to "Return Requests", return_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Special Requests", special_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link"%>
      <% end %>
      <% end %>
    </div>
  </div>
</nav>-->
<div class ="row m-2">
  <div class = "col-md-6">
    <h1>Store</h1>
  </div>
  <div class = "col-md-3">
    <form action="/items" method="GET">
      <label for="filter">Filter Options</label>
      <select name="filter" name="filter" onchange="this.form.submit()">
      <option value="All" <%= "selected" if session[:filter] == "All" %>>All</option>
      <option value="category" <%= "selected" if session[:filter] == "category" %>>Filter by category</option>
        <option value="brand" <%= "selected" if session[:filter] == "brand" %>>Filter by brand</option>
        <option value="remaining_quantity" <%= "selected" if session[:filter] == "remaining_quantity" %>>Filter by availabilty</option>
      </select>
      <% if session[:filter] == "category" %>
        <select name="filter_option" onchange="this.form.submit()">
          <option value="All">All</option>
          <% @items.uniq{|a| a.category}.each do |item| %>
            <option value="<%= item.category %>"><%= item.category %></option>
          <% end %>
        </select>
        <%= link_to "Clear Filter Options", items_url %>            
            
      <% elsif session[:filter] == "brand" %>
        <select name="filter_option" onchange="this.form.submit()">
          <option value="All">All</option>
          <% @items.each do |item| %>
            <option value="<%= item.brand %>"><%= item.brand %></option>
          <% end %>
        </select>
        <%= link_to "Clear Filter Options", items_url %>

      <% elsif session[:filter] == "remaining_quantity" %>
        <select name="filter_option" onchange="this.form.submit()">
          <option value="All">All</option>

          <option value="only_available">only available</option>         
        </select>
        <%= link_to "Clear Filter Options", items_url %>
      <% elsif session[:filter] == "All" %>
        <select name="filter_option" onchange="this.form.submit()">
          <option value="All">All</option>

          <option value="only_available">only available</option>         
        </select>  
        <%= params.inspect %>
      <% end %>
    </form>
  </div>
  <div class = "col-md-3">
    <h6><%= sortable "price", 'sort based on price' %></h6>
    <h6><%= sortable "special_item", 'sort based on popularity' %></h6>
  </div>
</div>
<% if @visitor or @isUser %>
  <div class = "row">
    <% @items.each do |item| %>
      <div class = "col-md-3 m-3 border rounded item_link" style = "text-align:center">
        <div style="height: 300px;">
          <div class="h-75 w-100" style="background-color: rgba(255,255,255,.3)">
            <% if item.photo.present? %>
              <div class = "d-inline-block" style = "padding:10px 10px">
                <%= image_tag item.photo.url(:medium) ,:class => "img-fluid", :style => "width = 100%"%>
              </div>
            <% else %>
              <div class = "d-inline-block" style = "padding:100px 20px">
                No image is available for this product.
              </div>
            <% end %>
          </div>
          <div class="h-25 w-100">
            <h4><%= link_to "#{item.name}", item, :class => "stretched-link home_links" %></h4>
          </div>
        </div>
      <% if current_user %>  
        <% if current_user.is_admin %>
          <div class = "row mb-3">
            <div class = "col-md-6" style="text-align:center">
              <%= link_to 'Edit', edit_item_path(item), :class => "btn btn-warning" %>
            </div>
            <div class = "col-md-6">
              <%= button_to 'X', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <table class = "table table-hover">
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Quantity</th>
      <th>Price</th> 
      <!--<th>Tax Slab</th>
      <th>Special Item</th> 
      <th>Age Restricted</th>-->       
      <th colspan="4" style = "text-align:center"><%= link_to '+ New Item', new_item_path, :class => "btn btn-warning" %></th>
    </tr>
    <tr>
    </tr>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to "#{item.name}", item %></td>
        <td><%= item.category %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
        <!--<td><%= item.tax_slab %></td>
        <td><%= item.special_item %></td>
        <td><%= item.age_restricted %></td>-->
        <!--
        <% if item.photo.present? %>
        <td><%= image_tag item.photo.url(:medium) %></td>
        <% end %>-->
        <td><%= link_to 'Show', item , :class => "btn btn-success"%></td>
        <% if current_user %>
          <!--<%# if item.quantity == 0 %>
            <td colspan = "3" style = "text-align: center"><%#= link_to "Add to Subscription List", items_url(:is_subscribing=> true, :item_id => item.id), :class => "btn btn-warning" %></td>  
          <%# else %>
            <td><%#= button_to 'Add to Cart', {:controller => "carts", :action => "create", :name => current_user.email, :cartItem => item.id, :item_id => item.id, :itemquantity => 1}, method: "post", :class => "btn btn-success" %></td>
            <td><%#= link_to 'Buy Now', quicktransaction_url(:itm_id => item.id),:class =>"btn btn-primary" %></td>
            <td><%#= button_to 'Add to Wishlist', {:controller => "wishlists", :action => "create", :wname => current_user.email, :wishlistItem => item.id}, method: "post", :class => "btn btn-info" %></td>
          <%# end %>-->
          <% if current_user.is_admin == true %>
            <td><%= link_to 'Edit', edit_item_path(item), :class => "btn btn-warning" %></td>
            <td><%= button_to 'X', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>
<% if current_user %>
  <% if current_user.is_admin == true %>
    <%#= link_to 'View Users', users_path %>
  <% end %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h1>Item Details</h1></td>
<div class = "row">
  <div class = "col-md-7">
    <p>
      <strong>Name:</strong>
      <%= @item.name %>
    </p>

    <% if @item.photo.present? %>
      <p><%= image_tag @item.photo.url(:medium) %></p>
    <% end %>

    <p>
      <strong>Category:</strong>
      <%= @item.description %>
    </p>

    <p>
      <strong>Quantity:</strong>
      <%= @item.quantity %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @item.price %>
    </p>

    <p>
      <strong>Tax slab:</strong>
      <%= @item.tax_slab %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @item.description %>
    </p>

    <p>
      <strong>Special Item:</strong>
      <%= @item.special_item %>
    </p>

    <p>
      <strong>Age Restricted Item:</strong>
      <%= @item.age_restricted %>
    </p>
  </div>
  <div class = "col-md-5">
    <% if current_user && current_user.is_admin %>
      <h3>Comments</h3>
      <% @item.comments.each do |comment| %>
          <p><strong>comment :</strong>: <%= comment.comment %></p>
      <% end %>
    <% end %>
    <br/>
    <h3>Give Feedback</h3>
    <%= form_for([@item, @item.comments.build]) do |f| %>
      <p>
        <%= f.text_area(:comment, {:class => 'form-control'}) %>
      </p>
      <p>
        <%= f.submit({:class => 'btn btn-success', :value => "Send"}) %>
      </p>
      <% end %>
      <% if current_user %>
        <% if current_user.is_admin == true %>
          <%= link_to 'Edit', edit_item_path(@item) ,:class => "btn btn-success"%>
          <% end %>    
      <% else %>
      <%= link_to 'Register to buy', new_user_registration_path, :class => "btn btn-warning" %>     
    <% end %>
  </div>
</div>

<% if current_user %>   
  <div class = "row">   
    <% if @item.quantity == 0 %>
      <div class = "col-md-4"><%= link_to "Add to Subscription List", items_url(:is_subscribing=> true, :item_id => @item.id), :class => "btn btn-warning" %></div>
    <% else %>
      <div class = "col-md-2">
        <%= button_to 'Add to Cart', {:controller => "carts", :action => "create", :name => current_user.email, :cartItem => @item.id, :item_id => @item.id, :itemquantity => 1}, method: "post", :class => "btn btn-outline-success" %>
      </div>
      <div class = "col-md-2">
        <%= link_to 'Buy Now', quicktransaction_url(:itm_id => @item.id),:class =>"btn btn-outline-primary" %>
      </div>
      <div class = "col-md-2">
        <%= button_to 'Add to Wishlist', {:controller => "wishlists", :action => "create", :wname => current_user.email, :wishlistItem => @item.id}, method: "post", :class => "btn btn-outline-info" %>
      </div>
    <% end %>
    <div class = "col-md-12">
      <br/><%= link_to 'Back', items_path, :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>