config/routes.rb
Rails.application.routes.draw do

  resources :special_items
  resources :return_items
  resources :homepages
  devise_for :admins
  resources :adminpages
  resources :items
  resources :items do
  resources :comments
  end
  resources :carts
  resources :wishlists
  resources :orders
  match '/users',   to: 'users#index',via: 'get'
  match "/users/:id" => "users#show", via: 'get'
  match "/users/:id/edit" => "users#edit", via: 'get'
  match "/users/new" => "users#new", via: 'get'
  
  devise_for :users ,:path_prefix => 'my'
  resources :users

  get '/transaction', to: 'transaction#index'
  get '/quicktransaction', to: 'quicktransaction#index'
  get '/returnrequestprocess', to: 'returnrequestprocess#index'
  get '/specialrequestprocess', to: 'specialrequestprocess#index'
  get '/otp', to: 'otp#index'
  get '/clearCart', to: 'clear_cart#index'
  post "otp_enter", to: 'otp#getNum'
  
  root to:"homepages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adminpage.rb
class Adminpage < ApplicationRecord
 	
 	attr_readonly :mail_id, :password	
    validates :CVV,
    	presence: true,
    	length: {maximum: 3},
    	on: :edit,
    	allow_nil: false
    validates :Credit_card_number,
    	presence: true,
    	length: {maximum: 16},
    	on: :edit,
    	allow_nil: false
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :item
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
    has_many :comments, dependent: :destroy
    validates_presence_of :name
    validates_presence_of :category
    validates_presence_of :brand
    validates_presence_of :price
    has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/return_item.rb
class ReturnItem < ApplicationRecord
end

app/models/special_item.rb
class SpecialItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/return_items_controller.rb
class ReturnItemsController < InheritedResources::Base
  
  def index
    @oc, @cc, @wc = calculate_counts()
    if params[:status_id]
      if current_user.is_admin
        @return_items = ReturnItem.where(["returnStatus = ?", params[:status_id]])
      else
        @return_items = ReturnItem.where(["returnuserId = ?", current_user.id]).where(["returnStatus = ?", params[:status_id]])
      end
    end
    
  end

  private
    def return_item_params
      params.permit(:returnuserId, :returnItemid, :returnTransactionId, :returnQuantity, :refundAmount)
    end

end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clear_cart_helper.rb
module ClearCartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/return_items_helper.rb
module ReturnItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/return_items/_form.html.erb
<%= form_with(model: return_item, local: true) do |form| %>
  <% if return_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(return_item.errors.count, "error") %> prohibited this return_item from being saved:</h2>

      <ul>
        <% return_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :returnuserId %>
    <%= form.number_field :returnuserId %>
  </div>

  <div class="field">
    <%= form.label :returnItemid %>
    <%= form.number_field :returnItemid %>
  </div>

  <div class="field">
    <%= form.label :returnTransactionId %>
    <%= form.text_field :returnTransactionId %>
  </div>

  <div class="field">
    <%= form.label :returnQuantity %>
    <%= form.number_field :returnQuantity %>
  </div>

  <div class="field">
    <%= form.label :refundAmount %>
    <%= form.text_field :refundAmount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/return_items/edit.html.erb
<h1>Editing Return Item</h1>

<%= render 'form', return_item: @return_item %>

<%= link_to 'Show', @return_item %> |
<%= link_to 'Back', return_items_path %>

app/views/return_items/index.html.erb
<!--<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3 rounded-bottom">
  <div class ="container">
    <div class="navbar-nav">
      <%= link_to "Store", items_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Wishlists (#{@wc})", wishlists_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Cart (#{@cc})", carts_url, method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Orders (#{@oc})", orders_url, method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Items Returned", return_items_url(:status_id => 1), method: "get", :class=>"nav-item nav-link"%>
      <%= link_to "Rejected Special Requests", special_items_url(:status_id => 2), method: "get", :class=>"nav-item nav-link"%>
      <% if current_user.is_admin == true %>
      <%= link_to "Return Requests", return_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link" %>
      <%= link_to "Special Requests", special_items_url(:status_id => 0), method: "get", :class=>"nav-item nav-link"%>
      <% end %>
    </div>
  </div>
</nav>-->
<% if @return_items %>
  <table class = "table table-hover">
    <thead>
      <tr>
        <% if current_user.is_admin %>
          <th>User</th>
        <% end %>
        <th>Item</th>
        <th>tid</th>
        <th>Quantity</th>
        <th>Refund</th>
        <% if current_user.is_admin %>
          <th colspan="3" style="text-align:center">Actions</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @return_items.each do |return_item| %>
        <tr>
          <% if current_user.is_admin %>
            <td><%= User.where(:id => return_item.returnuserId).last.email %></td>
          <% end %>
          <td><%= Item.where(:id => return_item.returnItemid).select("name").last.name  %></td>
          <td><%= return_item.returnTransactionId %></td>
          <td><%= return_item.returnQuantity %></td>
          <td><%= return_item.refundAmount %></td>
          <!--<td><%= link_to 'Show', return_item %></td>
          <td><%#= link_to 'Edit', edit_return_item_path(return_item) %></td>-->
          <% if return_item.returnStatus == 0 %>
            <% if current_user.is_admin %>
              <td></td>
              <td><%= link_to 'Approve', returnrequestprocess_url(:is_approved => "yes", :item_id => return_item.returnItemid, :user_id => return_item.returnuserId, :tid => return_item.returnTransactionId), :method => "get", :class => "btn btn-outline-primary" %></td>
              <td><%= link_to 'Reject', returnrequestprocess_url(:is_approved => "no", :item_id => return_item.returnItemid, :user_id => return_item.returnuserId, :tid => return_item.returnTransactionId), :method => "get", :class => "btn btn-outline-danger" %></td>
            <% end %>
          <% elsif current_user.is_admin %>
            <td colspan = "2" style = "text-align:center">None</td>
          <% end %>
          <!--<td><%#= link_to 'Destroy', return_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
<% else%>
  <h3>The list is empty.</h3>
<% end %>

<%= link_to 'Back', items_path , :class => "btn btn-primary"%>

app/views/return_items/new.html.erb
<h1>New Return Item</h1>

<%= render 'form', return_item: @return_item %>

<%= link_to 'Back', return_items_path %>

app/views/return_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Returnuserid:</strong>
  <%= @return_item.returnuserId %>
</p>

<p>
  <strong>Returnitemid:</strong>
  <%= @return_item.returnItemid %>
</p>

<p>
  <strong>Returntransactionid:</strong>
  <%= @return_item.returnTransactionId %>
</p>

<p>
  <strong>Returnquantity:</strong>
  <%= @return_item.returnQuantity %>
</p>

<p>
  <strong>Refundamount:</strong>
  <%= @return_item.refundAmount %>
</p>

<%= link_to 'Edit', edit_return_item_path(@return_item) %> |
<%= link_to 'Back', return_items_path %>